#interface_branding: Limine boot for Artix Linux

term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: 1e1e2e
term_foreground: cdd6f4
term_background_bright: 585b70
term_foreground_bright: cdd6f4


timeout: 6
#default_entry: 1
default_entry: Artix - AMD - main/Artix Linux (Zen)


/Artix - AMD - main
//+Artix Linux (Zen)
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux-zen
module_path: boot():/EFI/Linux/amd-ucode.img
module_path: boot():/EFI/Linux/initramfs-linux-zen.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-init

//Artix Linux (artix)
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux
module_path: boot():/EFI/Linux/amd-ucode.img
module_path: boot():/EFI/Linux/initramfs-linux.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-init

//Artix Linux (LTS)
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux-lts
module_path: boot():/EFI/Linux/amd-ucode.img
module_path: boot():/EFI/Linux/initramfs-linux-lts.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-init


/Artix - Intel
//Artix Linux (Zen)
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux-zen
module_path: boot():/EFI/Linux/intel-ucode.img
module_path: boot():/EFI/Linux/initramfs-linux-zen.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-ini

//Artix Linux (artix)
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux
module_path: boot():/EFI/Linux/intel-ucode.img
module_path: boot():/EFI/Linux/initramfs-linux.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-init

//Artix Linux (LTS)
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux-lts
module_path: boot():/EFI/Linux/intel-ucode.img
module_path: boot():/EFI/Linux/initramfs-linux-lts.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-init

/Artix Linux (LTS) - Fallback - no ucode
protocol: linux
kernel_path: boot():/EFI/Linux/vmlinuz-linux-lts
module_path: boot():/EFI/Linux/initramfs-linux-lts.img
cmdline: root=PARTUUID=9cbafe9d-1cbd-4f9e-9b33-a63240b432d8 rw init=/usr/bin/openrc-init
